version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:./data/incidentdb
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./data:/data  # Volume para persistir dados do H2
